version: "3.8"

services:
  ml-model:
    build:
      context: ./ml-model
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ml_models:/app/models

  api:
    build:
      context: ./MyHealth.Api
      dockerfile: Dockerfile
    ports:
      - "5144:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      ml-model:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./health-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5144/api/health/assess-simple
    depends_on:
      api:
        condition: service_healthy

volumes:
  ml_models:

networks:
  default:
    driver: bridge
